handle data salesforce
eduNEXT/crm-integration-xblock pull request #2
Opened 2017-12-18 20:54 UTC by dfrojas

2017-12-18 22:22 UTC, felipemontoya requested changes

2017-12-18 22:22 UTC, felipemontoya commented on crm_integration_xblock/crm_integration_xblock.py
> +            sf_varkey = SalesForceVarkey(method)
El hecho de utilizar este objeto, u otro objeto de datos, podriamos hacerlo configurable y tener un mapa (dict) de clases y de nombres. O incluso usar un import dinamico. Haciendo eso, lo que ganamos es que podemos tener todas las validaciones de varkey en el objeto varkey y luego podrían convivir otras validaciones en otro objeto diferente (ej, otro cliente, o otro proyecto diferente del mismo varkey)

2017-12-18 22:22 UTC, felipemontoya commented on crm_integration_xblock/crm_integration_xblock.py
> +            if salesforce_object == "Historial_escuela__c":
todas estas revisiones si el objeto es `historial_escuela` o `escuela_c` o lo que sea, deberiamos meterlas dentro del mismo objeto que hace la revisión. Así pues podriamos tener un solo metodo `validate` que decide que tipo de validación se usa, según el `salesforce_object` que le estemos pasando

2017-12-18 22:22 UTC, felipemontoya commented on crm_integration_xblock/crm_integration_xblock.py
> +            if salesforce_object == "Proyectos__c":
volver `validate`

2017-12-18 22:22 UTC, felipemontoya commented on crm_integration_xblock/crm_integration_xblock.py
> +                return sf_varkey.validate_by_project(token, instance_url, salesforce_object, data, username)
volver `validate`

2017-12-18 22:22 UTC, felipemontoya commented on crm_integration_xblock/crm_integration_xblock.py
> +                return sf_varkey.summary(token, instance_url, username)
volver `validate`

2017-12-18 22:22 UTC, felipemontoya commented on crm_integration_xblock/crm_integration_xblock.py
> +            if salesforce_object == "Historial_escuela__c":
de hecho si te fijas, todas las validaciones de abajo realmente tienen la misma firma (signature) así que es muy facil agruparlas

2017-12-18 22:22 UTC, felipemontoya commented on crm_integration_xblock/varkey_validations.py
> +class SalesForceVarkey():
class Nombre(object)

2017-12-18 22:22 UTC, felipemontoya commented on crm_integration_xblock/salesforce_tasks.py
> +class SalesForceTasks():
cual es la razón de tener estas 2 clases separadas si finalmente ambas tienen quemadas las validaciones de varkey? hace sentido unirlas?

2017-12-18 22:22 UTC, felipemontoya commented on crm_integration_xblock/salesforce_tasks.py
> +class SalesForceTasks():
Hay forma de que extraigamos la parte generica como get_token o el hecho de hacer un post o un patch a una superclase y dejar todo lo que es especifico de varkey en un solo lugar?

2017-12-19 21:25 UTC, felipemontoya requested changes

2017-12-19 21:25 UTC, felipemontoya commented on crm_integration_xblock/crm_integration_xblock.py
> +    name = String(help="Please write the name of your company",
esta variable sería mucho más descriptiva si se llamara backend_name. Y en help puedes poner "Please write the name of the backend. Normally it is the name of the project you are working on"

2017-12-19 21:25 UTC, felipemontoya commented on crm_integration_xblock/crm_integration_xblock.py
> +    name = String(help="Please write the name of your company",
precisamente para el caso en el que varkey pueda tener más de un backend

2017-12-19 21:25 UTC, felipemontoya commented on crm_integration_xblock/salesforce_tasks.py
> +        In SalesForce's Varkey are handle 5 objects:
este metodo lo llamas varias veces desde la clase SalesForceVarkey y de hecho tiene un montón de logica de varkey. Estas seguro que va en la clase padre y no en la hija?

2017-12-19 21:25 UTC, felipemontoya commented on crm_integration_xblock/salesforce_tasks.py
> +
aquí en esta clase, falta la definición del metodo `validate` así solo haga `raise NotImplementedError`

2017-12-19 21:25 UTC, felipemontoya commented on crm_integration_xblock/varkey_validations.py
> +                    "tic_dimension_1": tic_dimension_1__c}
en esta clase si falta el propio metodo validate que decide a cual de los otros metodos llamar

2017-12-20 06:36 UTC, dfrojas commented on crm_integration_xblock/varkey_validations.py
> +        if salesforce_object == "Historial_escuela__c":
Para evitar estos if, implementé un diccionario tal como llamábamos la clase, pero fallaba en que repetía el request de create_or_update 3 veces, es decir, en los tres métodos donde se llamabada, validate_cue_by_user, validate_by_project y validate_cue.

2017-12-20 14:29 UTC, felipemontoya requested changes
En general se nota mucho el trabajo. Porfa pegale una mirada a la opción de heredar de una clase a la otra, y a los otos 2 comentarios pequeños y quedamos listos para hacer merge

2017-12-20 14:29 UTC, felipemontoya commented on crm_integration_xblock/varkey_validations.py
> +class SalesForceVarkey():
por que no hiciste a esta clase subclase de la de `SalesForce`. Si lo hicieras, puedes garantizar que la firma de los objetos que luego vas a usar en el xblock siempre sea correcta.

2017-12-20 14:29 UTC, felipemontoya commented on crm_integration_xblock/varkey_validations.py
> +        self.salesforce = SalesForce(token, instance_url)
si la vuelves subclase, aquí lo que harías sería hacer `super(SalesForceVarkey, self).__init__(token, instance_url)`. Bueno, de hecho sería lo primero que hagas en este metodo

2017-12-20 14:29 UTC, felipemontoya commented on crm_integration_xblock/varkey_validations.py
> +        if salesforce_object == "Historial_escuela__c":
Ni idea por que, habría que ver la implementación, pero ya dentro de esta clase, me parece menos grave la sucession de `if`s

2017-12-20 15:41 UTC, felipemontoya approved these changes
Listo, yo lo veo bien para darle merge.

2017-12-20 15:50 UTC, merged